# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Builds and uploads the app to TestFlight"
  lane :testflight_distribution do
    api_key = app_store_connect_api_key(
      key_id: ENV['KEY_ID'],
      issuer_id: ENV['ISSUER_ID'],
      key_content: ENV['KEY_CONTENT'],
      is_key_content_base64: true,
      in_house: false,
    )

    match(
      type: "adhoc",
      api_key: api_key,
      app_identifier: ENV['APP_IDENTIFIER'],
      force_for_new_devices: true,
      readonly: true
    )

    gym(
      workspace: "host.xcworkspace",
      scheme: "host",
      configuration: "Release",
      export_method: "ad-hoc",
    )

    pilot(
      app_identifier: ENV['APP_IDENTIFIER'],
      skip_waiting_for_build_processing: true,
      api_key: api_key,
    )
  end
end
